### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by YoichiroKimoto** [YoichiroKimoto/chat-space#11]
#IPアドレス
18.180.40.17

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**ビューの崩れ**
仕様書通りにビューを整えましょう
<img width="1446" alt="ChatSpace" src="https://user-images.githubusercontent.com/44963290/83252548-622eb680-a1e6-11ea-83f7-c5eb17cf5c84.png">



お手本
<img width="1436" alt="ChatSpaceお手本" src="https://user-images.githubusercontent.com/44963290/77241111-2fd66b00-6c31-11ea-9b28-57bd4507b588.png">



参考カリキュラム:https://master.tech-camp.in/curriculums/3944
<img width="867" alt="ヘッダー" src="https://user-images.githubusercontent.com/44963290/77241139-85127c80-6c31-11ea-8f1d-da109523e77c.png">
<img width="865" alt="メッセージ記入欄" src="https://user-images.githubusercontent.com/44963290/83252582-770b4a00-a1e6-11ea-91f6-74d5d03e4700.png">


修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by YoichiroKimoto** [comment]
修正しました

**Comment by mo1015** [comment]
再提出ありがとうございます！
投稿フォームの修正ができていないようです。
本番環境で実装できているかもう一度確認をお願いします！

修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by YoichiroKimoto** [comment]
投稿フォーム、見直しました

**Comment by mo1015** [comment]
再提出ありがとうございます！
挙動確認させて頂いたところ、投稿フォームのサイズが見本と異なります。
カリキュラムを参考に修正しましょう！
↓
<img width="691" alt="投稿フォーム見本" src="https://user-images.githubusercontent.com/62644781/83320329-6d82f000-a281-11ea-9d44-a5d6478126b1.png">


修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by YoichiroKimoto** [comment]
Type a messageの左側がはみ出しているのかなと思い修正しました

**Comment by mo1015** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

※今後実装に関する質問がありましたら、メンターに確認をお願いします！

**Comment by YoichiroKimoto** [comment]
ありがとうございました
